### ISSUE TITLE
Problem in lastrun

### ISSUE THREAD

**Issue by fmido88** [sebsoftnl/moodle-tool_usersuspension#8]
$lastrun = static::get_lastrun_config('smartdetect', 0, true);
        $deltatime = time() - $lastrun;
        if ($deltatime < config::get('smartdetect_interval')) {
            return false;
        }

In this when autoreset turn true, the last run always set a new value even if the task not realy operated.
I think it should be like this

$lastrun = static::get_lastrun_config('smartdetect', 0, false);
        $deltatime = time() - $lastrun;
        if ($deltatime < config::get('smartdetect_interval')) {
            return false;
        }
static::set_lastrun_config('smartdetect');

So the new config reset only when that task operated.

**Comment by rogiervandongen** [comment]
Will be fixed in new version (released this week)
